### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ashhadali10** [nrednav/final-year-project#1]
bhai ap ka project use kr skta hon main kya??

**Comment by Zaibali9999** [comment]
Public hai sab use kar sakty hain :P

**Comment by souravmaji1** [comment]
brother , when i type "npm install " in client folder it giving error can you please help me to solve the error

**Comment by Waseem-javed** [comment]
delete package-lock.json file

**Comment by souravmaji1** [comment]
Ok brother

**Comment by souravmaji1** [comment]
brother , same error showing after deleting package.lock.json file

**Comment by souravmaji1** [comment]
brother , now i am able to run 'npm install' in oracles , server folder but not working in client folder

**Comment by souravmaji1** [comment]
hi brother , i was trying and finally i have successfully able to run "npm install " in client,server,oracle folder but now when i type pm2 start in root folder again new error showing

![chota](https://user-images.githubusercontent.com/87080195/170490051-0cb95ca3-cb1a-4481-94f0-d1d63fcc1ee3.PNG)

**Comment by Waseem-javed** [comment]
nope just run in server folder and then go back from server folder and pm2
start or pm2 log

**Comment by souravmaji1** [comment]
pm2 start in root folder right ?

**Comment by souravmaji1** [comment]
what would i run in server folder ?

**Comment by Waseem-javed** [comment]
just install the dependencies in server folder and run pm2 start or logs in
root folder. they will start th all server

**Comment by souravmaji1** [comment]
i have typed the 'npm install' command and when i get back to root folder and run the pm2 start command it shows the above error

**Comment by souravmaji1** [comment]
brother , it is showing this

![tinkumother](https://user-images.githubusercontent.com/87080195/170493208-b2f4371d-70f6-4003-be82-71365a207679.PNG)

**Comment by souravmaji1** [comment]
hi brother, I have managed to reach uptill this step and i believe that this is the last error and after that i will able to run this application in localhost so can you help me to solve this last error


![last](https://user-images.githubusercontent.com/87080195/170735980-8558e057-f3d5-434b-b7cc-57371f482e19.PNG)

**Comment by Zaibali9999** [comment]
ok your client and server application is running but other things are not working correctly 
you can start these things manually

**Comment by Zaibali9999** [comment]
But there are other alot of error in this project i m trying to solve those issues

**Comment by Zaibali9999** [comment]
0x0000000000000000000000000000000000000000
contract returned this holding address with error which is not correct 
Error: This contract object doesn't have address set yet, please set an address first.

**Comment by thexahmed00** [comment]
@Zaibali9999  @souravmaji1 is this project working?

**Comment by Zaibali9999** [comment]
Yes
