### ISSUE TITLE
truffle migrate --network development --reset error 

### ISSUE THREAD

**Issue by faisalashrafwani** [nrednav/final-year-project#2]
While navigating to the contracts directory it is throwing this error.
===========================
> Everything is up to date, there is nothing to compile.
> Something went wrong while attempting to connect to the network at undefined. Check your network configuration.
connection not open on send()
Truffle v5.5.3 (core: 5.5.3)
Node v17.6.0
![Screenshot from 2022-03-05 16-02-14](https://user-images.githubusercontent.com/76038623/156879549-343b09f8-cebb-4ed4-a8f6-ebb880eead74.png)

It would help me in further understanding this project, thank you

**Comment by Zaibali9999** [comment]
Error: could not find any accounts

**Comment by Zaibali9999** [comment]
2|verifier | Error: could not find any accounts
2|verifier | [object Object]

**Comment by Zaibali9999** [comment]
4|escrow_oracle  | node:internal/modules/cjs/loader:936
4|escrow_oracle  |   throw err;
4|escrow_oracle  |   ^
4|escrow_oracle  | Error: Cannot find module 'form-data'

**Comment by souravmaji1** [comment]
hi brother, I have managed to reach uptill this step and i believe that this is the last error and after that i will able to run this application in localhost so can you help me to solve this last error

![last](https://user-images.githubusercontent.com/87080195/170692716-5c2c7f19-48ab-4091-b77e-a2db9a9ac6a7.PNG)

**Comment by Zaibali9999** [comment]
For truffle
Turn on ganachi-cli
