### ISSUE TITLE
Holding Deposit Oracle is not working

### ISSUE THREAD

**Issue by divyeshdesanisos** [nrednav/final-year-project#5]
Hello there,

First of all thank you very much for preparing this project. It has end to end - what a project blockchain based project needs.

I have successfully setup the whole project on my windows 10 system. I have followed all the steps till 'Buyer' need to pay deposit.

'Buyer' get the request to pay the deposit, but when clicking on the button following error occurred.
![image](https://user-images.githubusercontent.com/96718718/194559569-ad0810ae-3e05-4acb-b204-1b9c548a4ceb.png)

When I looked into the code I found that there are 3 oracles used in the project setup.
  - Verfier
  - Holding Deposit and
  - Escrow

In the 'Oracles' - all oracle.js are using contracts.js files (where for holdingDeposit and Escrow - there are factory version and not for verifier) - not sure why.

However in the hdOracle.js file hd and escrow (in the import) are not using the factory version but holdingDeposit.js and escrow.js (which are internally using build version of contracts) and not holdingDepositFactory.js and escrowFactory.js - respectively. I tried to use the factory version but it is still throwing some other error that some function is missing. Let me know if you need more information.

![image](https://user-images.githubusercontent.com/96718718/194562043-a59fb52d-8f84-46f9-a4a1-faefcfb9b667.png)

In the 'Contracts' - I found that there are only factory versions are being deployed (which are taking abi and address from myconfig file)

![image](https://user-images.githubusercontent.com/96718718/194561025-2e81f168-ef23-4386-8f1e-fceb23c3b908.png)

Can you please help me solve the error in the screenshot 1? - when buyer click on 'Pay Deposit' button.

Thanks in advaance.

**Comment by Yashda486** [comment]
As you have completed the project, can you please help me how to overcome this error.
![block](https://user-images.githubusercontent.com/71481239/205433378-2327b2a7-6e78-41cf-9fd0-0d15866d902e.png)

**Comment by nrednav** [comment]
Fixed in: https://github.com/nrednav/final-year-project/commit/0757a61937c97a3c0ee9e8e7c7bd906b43043f0c
