### ISSUE TITLE
syntax for defining volumes is incorrect.

### ISSUE THREAD

**Issue by dhirajbit** [nrednav/final-year-project#8]
error: volumes.authority1 value 'authority2', 'ipam' do not match any of the regexes: '^x-'

The definition of 'authority1' and 'authority2' is incorrect. They are defined on the same line without a colon separator. Also, the mongodb-data and MongoDB-config are defined in the same line without a colon separator.

The ipam section should be placed under the networks section, not under the volumes section.

**Comment by nrednav** [comment]
Fixed in: https://github.com/nrednav/final-year-project/pull/9
